### ISSUE TITLE
你好, 支持编译java代码字符串编译吗?包括对已经编译的字符串class进行热更新

### ISSUE THREAD

**Issue by lerambo** [EB-wilson/JavaDynamilizer#2]
你好, 支持编译java代码字符串编译吗?包括对已经编译的字符串class进行热更新 #2

**Comment by EB-wilson** [comment]
可以详细一些描述么？关于“已经编译的字符串class”
你可能是指用字符串的形式编写java程序并尝试加载它，就像javassist那样，但是目前我没有计划编写词法分析和语法树解析，比较鼓励使用抽象的树形结构编辑字节码。
关于热更新的话，该框架暂时没有实现对已经加载到内存的类信息更新的功能，实现的仅仅是一个对对象的动态委托，暂时没有实现对已经被加载的类型进行热更新，未来可能会有实现的尝试，但是现在如果您可以管理一个类型可能存在的所有实例的话，尽可能将它们都动态化，采取动态类型进行热更新是比较稳妥的方式
